### PR TITLE
fix typos in "On PPK’s moratorium on new browser features"

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by pepelsbey** [comment]
@cvan, “immediacy.” is not a typo, it’s just a British style, see [British versus American style](http://www.thepunctuationguide.com/british-versus-american-style.html).

**Comment by pepelsbey** [comment]
cc @brucelawson

**Comment by pepelsbey** [comment]
Partially fixed in #322, thank you!

**Comment by cvan** [comment]
> @cvan, “immediacy.” (and other cases) is not a typo, it’s just a British style, see British versus American style.

that's what I thought, but then I saw this quotation usage in the [first paragraph](https://github.com/operasoftware/devopera/blob/master/blog/_posts/2015-08-03-on-a-moratorium-on-new-browser-features.md):

> Famed developer and commentator Peter Paul Koch (PPK) recently called for “a moratorium on new browser features for about a year or so.”

either way, I can remove the quotation changes.

<hr>

the other two remaining issues are with a [comma](https://github.com/operasoftware/devopera/pull/321/files#diff-e46d207dd3d581803cd7a56fd2832d85R99) and ["end-user"](https://github.com/operasoftware/devopera/pull/321/files#diff-e46d207dd3d581803cd7a56fd2832d85R101).

**Comment by pepelsbey** [comment]
I asked @brucelawson to review your PR and he got all needed parts from it and applied in #322. Not sure about commas and “end-user” but it’s totally Bruce’s call what changes to make.

**Pull request closed without merging**
