### PR TITLE
Update 2015-04-09-ux-accessibility-aria-label.md

### PR DESCRIPTION
**Pull request by webhipster**
Remove "press me to" as verbose calls to action have been abused and keeping examples free of them will help keep them at bay.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
CC @Heydon

**Comment by brucelawson** [comment]
Hmm.
"verbose calls to action have been abused " < citation needed.
(I think it's pretty obvious that this is explanatory text rather than a code sample to be copied and re-used.)

**Comment by pepelsbey** [comment]
@Heydon, what do you think: is worth merging? Otherwise I’ll just close it.

**Comment by Heydon** [comment]
I don't think it's worth it, no. Thanks!

**Pull request closed without merging**
