### PR TITLE
Added note on subpixel antialiasing

### PR DESCRIPTION
**Pull request by Aides359**
Noted additional side effect of will-change where a new compositor layer causes blurry content.

### CODE REVIEW

**Comment by pepelsbey** [comment]
@SaraSoueidan, do you agree with proposed change to your article?

**Comment by SaraSoueidan** [comment]
@pepelsbey Is there a live demo somewhere or some example I could look at? I've not heard or see n this side effect before. We could also ping Paul Lewis who tech-edited the article for confirmation as well.

**Comment by pepelsbey** [comment]
@paullewis, could you please confirm the following addition to the `will-change` article?

> Lastly as stated before some changes of `will-change` result in the creation of a new compositor layer. The GPU however does not support subpixel antialiasing as done by the CPU in most browser, which will sometimes result in blurry content (especially with text).

**Comment by Aides359** [comment]
Sorry for the wait, this fell off my radar

See [this fiddle](https://jsfiddle.net/Aides/3zxg7cnj/) for a demo (tested on Chrome v52.0)

**Comment by pepelsbey** [comment]
@Aides359, now I see. Merged, thank you.

**Pull request merged**
