### PR TITLE
New extensions homepage

### PR DESCRIPTION
**Pull request by shwetank**
and other fixes to the ext docs as well (native messaging and address bar tutorials).

### CODE REVIEW

**Comment by pepelsbey** [comment]
@shwetank, have you seen [my comments](https://github.com/operasoftware/devopera/pull/485#issuecomment-230827438)?

> cover size should be 640×424

**Comment by shwetank** [comment]
Yes I did. I took a look at the cover images of previous article related to extension developer interviews, but none were of the size you mentioned as well. Right now, it still looks pretty good. I can of course resize them right now if you want, but would rather push out this PR as it already has so many changes. I could work on the image resizing sometime later today or tommorow.

**Comment by pepelsbey** [comment]
Let’s split our resposibilities here: I’ll work on design and code and the rest related things while you can focus on the content in `*.md` files. Otherwise it will lead to a mess in the code and design. You can always ask me to implement changes in design and I’m happy to do it (you saw how it works in sidebar case), but I prefer to do it myself.

Please don’t merge this PR, I’ll clean it up first.

**Comment by shwetank** [comment]
Sure thing. Works for me. Won't merge this PR ... will wait for you to merge it.

**Pull request merged**
