### PR TITLE
hover media feature in Chrome was broken prior to M-41

### PR DESCRIPTION
**Pull request by cvrebert**
See https://code.google.com/p/chromium/issues/detail?id=441613

### CODE REVIEW

**Comment by cvrebert** [comment]
CC: @patrickhlauke

**Comment by patrickhlauke** [comment]
LGTM in principle, but I'd add a comma just before the "although" and change the "&" to "and" :)

**Comment by pepelsbey** [comment]
@cvrebert, could you please resolve conflicts to make this PR mergeable and apply Patrick’s suggestions?

**Comment by cvrebert** [comment]
@pepelsbey Revision completed.

**Comment by pepelsbey** [comment]
Thank you!

**Pull request merged**
