### PR TITLE
Fix markup and convert it to Markdown

### PR DESCRIPTION
**Pull request by pepelsbey**
Fixes [Ragnarök — Viking Browser With HTML5 Parser!](https://dev.opera.com/blog/ragnarok-viking-browser-with-html5-parser/).

### CODE REVIEW

**Comment by fsoder** [comment]
Thanks!

**Comment by pepelsbey** [comment]
Any chance you can also deploy it? It seems like auto deploy we used to have is not working anymore.

**Comment by pepelsbey** [comment]
Oh, it just took some time :) Thanks!

**Comment by fsoder** [comment]
Yeah, just takes some time =).

**Pull request merged**
