### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pra85**
Recently I did a few PRs fixing typos. Then I took upon myself to find the typos in all posts. This is consolidated PR which fixes 50 typos I found while reading blog posts. Most of the typos are simple ones (like spelling mistakes or extra words) but some fix the indentation of the text which otherwise caused markup issues (like for example https://dev.opera.com/blog/what-s-new-in-opera-development-snapshots-4-november-2011-edition/ )

Wanted to make it clear, that I don't want to disrespect anyone with my fixes  just want to improve the overall quality of posts. 

I have listed all the changes I did in this pull request below - 

In `src/tv/_posts/2012-09-05-functional-keys-in-opera-tv-browsers.md`

1. Remove extra `or`

In `src/tv/_posts/2012-02-10-html5-audio-video-in-opera-tv-store-apps.md`

2. Spelling mistake - embeded > embedded

In `src/tv/_posts/2012-02-09-design-considerations-for-opera-tv-store-applications.md`

3. Spelling mistake - aproximate > approximate

In `src/blog/_posts/2015-10-27-opera-33.md`

4. Spelling mistake - compeleted > completed

In `src/blog/_posts/2014-08-08-web-notifications-in-opera-developer-25.md`

5. Spelling mistake - notitifcations > notitifcations
6. Spelling mistake - seperate > separate

In `src/blog/_posts/2014-04-24-browser-update-news.md`

7. Replace a with an

In `src/blog/_posts/2013-07-30-introducing-nex.md`

8. Spelling mistake - programatically > programmatically

In `src/blog/_posts/2013-07-02-introducing-opera-15-for-desktop-and-a-fast-release-cycle.md`

9. Remove extra in

In `src/blog/_posts/2013-05-28-browserjs-for-blink-based-opera.md`

10. Spelling mistake - neccessary > necessary

In `src/blog/_posts/2013-02-12-300-million-users-and-move-to-webkit.md`

11. Spelling mistake - compatibilty > compatibility

In `src/blog/_posts/2012-05-11-new-stable-release-improved-color-picker.md`

12. Spelling mistake - browers > browsers

In `src/blog/_posts/2012-03-26-whats-new-in-opera-development-snapshots-march-26-2012.md`

13. Spelling mistake - iteresting > interesting
14. Spelling mistake - contructor > constructor
15. Spelling mistake - Psuedo > Pseudo

In `src/blog/_posts/2012-02-10-implementing-do-not-track-opera.md`

16. Spelling mistake - satisfay > satisfy
17. Spelling mistake - Adveristing > Advertising

In `src/blog/_posts/2012-02-01-interview-on-w3c-blog.md`

18. Remove extra but

In `src/blog/_posts/2011-12-06-hello-opera-11-60.md`

19. Spelling mistake - contruct > construct

In `src/blog/_posts/2011-11-07-what-s-new-in-opera-development-snapshots-4-november-2011-edition.md`

20. Wrong indentation causing everything to appear as code block - Check https://dev.opera.com/blog/what-s-new-in-opera-development-snapshots-4-november-2011-edition/

In `src/blog/_posts/2011-10-21-html5-multimedia-bruces-frontrow-krakow-poland-presentation.md`

21. Remove empty li element

In `src/blog/_posts/2011-10-06-bruces-fronteers-presentation-html5-semantics.md`

22. Spelling mistake - targetting > targeting

In `src/blog/_posts/2011-09-29-what-s-new-in-opera-development-snapshots-28-september-2011-edition.md`

23. Spelling mistake - omited > omitted

In `src/blog/_posts/2011-08-10-opera-dragonfly-1-1-release-candidate-1.md`

24. Spelling mistake - Inpsector > Inspector

In `src/blog/_posts/2011-07-06-getusermedia-and-device-orientation-adventures.md`

25. Remove extra dot

In `src/blog/_posts/2011-06-28-opera-11-50-released-speed-dial-extensions-improved-standards-support.md`

26. Remove extra a

In `src/blog/_posts/2011-06-22-what-s-new-in-opera-development-snapshots-21-june-2011.md`

27. Wrong indentation causing everything to appear as code block - Check https://dev.opera.com/blog/what-s-new-in-opera-development-snapshots-21-june-2011/

In `src/blog/_posts/2011-04-06-implementing-html5-details.md`

28. Remove extra a

In `src/blog/_posts/2011-02-28-webgl-and-hardware-acceleration-2.md`

29. Spelling mistake - compatbile > compatible

In `src/blog/_posts/2011-02-22-ragnarok-viking-browser-with-html5-parser.md`

30. Replace a with an
31. Replace a with an

In `src/blog/_posts/2011-01-26-an-opera-of-creativity-at-naconf.md`

32. Spelling mistake - surpressing > suppressing

In `src/blog/_posts/2011-01-18-tokenizer-performance.md`

33. Spelling mistake - dirrectly > directly

In `src/blog/_posts/2010-12-10-aria-highlighting-extension-2.md`

34. Spelling mistake - stylehseets > stylesheets

In `src/blog/_posts/2010-12-06-opera-11-snapshot-1128.md`

35. Remove extra the

In `src/blog/_posts/2010-12-03-getting-opera-dragonfly-ready-for-opera-11.md`

36. Missing space

In `src/blog/_posts/2010-11-23-first-browser-to-11-unless-chrome-gets-there-first.md`

37. Remove extra the

In `src/blog/_posts/2010-11-19-postcards-from-tpac.md`

38. Missing space
39. Remove extra will

In `src/blog/_posts/2010-11-01-html5-and-css-3-at-staffordshire-university-2.md`

40. Spelling mistake - vsited > visited

In `src/blog/_posts/2010-10-21-opera-11-alpha-another-puzzle-piece.md`

41. Replace the with to

In `src/blog/_posts/2010-10-01-html5-forms-error-reporting-with-wobbly-bubbles.md`

42. Missing space

In `src/blog/_posts/2010-09-24-stockholm-presentation-and-links.md`

43. Spelling mistake - vsited > visited

In `src/blog/_posts/2010-09-12-over-the-air-2010-bruce-lawsons-web-developments-2-0-talk.md`

44. Spelling mistake - vsited > visited
45. Remove extra the

In `src/blog/_posts/2010-07-20-bruce-at-europython-2010.md`

46. Spelling mistake - delighed > delighted

In `src/blog/_posts/2010-05-25-scotch-on-the-rocks-coldfusion-conference.md`

47. Spelling mistake - familair > familiar

In `src/blog/_posts/2010-05-05-dibi-conference-gateshead-uk-wednesday-28th-april-2010.md`

48. Wrong indentation causing half the page to appear as code block - Check https://dev.opera.com/blog/dibi-conference-gateshead-uk-wednesday-28th-april-2010/
49. Spelling mistake - prototying > prototyping

In `src/blog/_posts/2010-03-03-everything-you-need-to-know-about-html5-video-and-audio-2.md`

50. Spelling mistake - enugh > enough

I hope to sit and check through all the remaining blog posts for typos as well.

### CODE REVIEW

**Comment by pra85** [comment]
Updated this PR with more typos that I found.

Here is the list of other changes I did -

In `src/blog/_posts/2010-03-02-opera-10-50-final-for-windows-is-out.md`

51. Replace a with an

In `src/blog/_posts/2010-02-25-opera-10-50-beta-for-mac-out-now.md`

52. Spelling mistake - standlone > standalone
53. Spelling mistake - usefull > useful

In `src/blog/_posts/2009-12-18-native-json-support-in-opera.md`

54. Spelling mistake - comitted > committed

In `src/blog/_posts/2009-11-05-the-lengths-to-go-to-to-get-a-site-fixed.md`

55. Capitalize i

In `src/blog/_posts/2009-11-03-improved-element-highlight-lands-in-opera-mobile-10-beta.md`

56. Spelling mistake - dubugging > debugging

In `src/blog/_posts/2009-09-06-svg-kung-fu.md`

57. Spelling mistake - conjuction > conjunction

In `src/blog/_posts/2009-09-03-font-face-web-fonts-resources.md`

58. Replace an with a

In `src/blog/_posts/2009-08-19-how-do-we-educate-the-web-standards-kids.md`

59. Spelling mistake - illustative > illustrative
60. Spelling mistake - exeriences > experiences
61. Spelling mistake - priviledge > privilege

In `src/blog/_posts/2009-07-30-the-html-5-experiments.md`

62. Spelling mistake - demoes > demos

In `src/blog/_posts/2009-05-19-opera-mama-a-sneak-peek-at-headings-images-and-summary.md`

63. Remove extra space between dirty and analysis
64. Spelling mistake - bmisuse > misuse

In `src/blog/_posts/2009-05-06-ukraine-university-tour-april-2009.md`

65. Spelling mistake - transation > translation
66. Spelling mistake - thiking > thinking
67. Spelling mistake - equlvalents > equivalents
68. Spelling mistake - numberous > numerous
69. Spelling mistake - intersted > interested

In `src/blog/_posts/2009-04-28-optimise-generated-svg-files-with-scour.md`

70. Replace a with an

In `src/blog/_posts/2009-04-08-opera-s-site-patching.md`

71. Spelling mistake - accomodate > accommodate
72. Spelling mistake - patcing > patching

In `src/blog/_posts/2009-04-03-malaysian-open-source-community-meetup.md`

73. Spelling mistake - openess > openness

In `src/blog/_posts/2009-04-02-european-accessibility-forum-frankfurt.md`

74. Spelling mistake - pleasent > pleasant
75. Spelling mistake - quesries > queries

In `src/blog/_posts/2009-03-26-geolocation-enabled-build.md`

76. Spelling mistake - relased > released

In `src/blog/_posts/2009-02-25-new-in-opera-presto-2-2-tls-1-2-support.md`

77. Spelling mistake - extenstion > extension (2 instances)

In `src/blog/_posts/2009-02-14-surfing-at-bondi.md`

78. Replace a with an ( 4 instances )

In `src/blog/_posts/2009-02-05-carakan.md`

79. Spelling mistake - eliminte > eliminate

In `src/blog/_posts/2009-01-26-testing-times.md`

80. Replace a with an

In `src/blog/_posts/2008-12-17-accessibility-supported-web-content-technologies-in-wcag-2-0.md`

81. Spelling mistake - programatically > programmatically ( 2 instances )

In `src/blog/_posts/2008-12-11-wcag-2-0-is-now-official-2.md`

82. Spelling mistake - accomodate > accommodate

In `src/blog/_posts/2008-12-09-2008-the-year-the-web-grew-up.md`

83. Spelling mistake - gtting > getting

In `src/blog/_posts/2008-12-04-opera-10-alpha-web-fonts-acid3.md`

84. Spelling mistake - highights > highlights
85. Spelling mistake - forseeable > foreseeable

In `src/blog/_posts/2008-11-25-video-3d-canvas-and-file-io-repeat.md`

86. Spelling mistake - applcations > applications

In `src/blog/_posts/2008-11-04-wcag-2-0-3.md`

87. Remove extra the

In `src/blog/_posts/2008-10-30-introducing-opera-dragonfly-alpha-3.md`

88. Spelling mistake - announcments > announcements
89. Replace a with an ( 2 instances )

In `src/blog/_posts/2008-10-30-have-you-got-the-x-factor-building-websites-for-mobile-and-disabled-users.md`

90. Spelling mistake - intrested > interested
91. Spelling mistake - accomodating > accommodating

In `src/blog/_posts/2008-10-22-uk-university-tour-web-standards-for-the-future.md`

92. Spelling mistake - cutomised > customised

In `src/blog/_posts/2008-10-20-opera-mobile-9-5-beta-2-and-the-x-widget-challenge.md`

93. Replace a with an ( 2 instances )

In `src/blog/_posts/2008-10-07-response-browser-standards-consultation.md`

94. Spelling mistake - guideines > guidelines

In `src/blog/_posts/2008-09-26-perils-browser-sniffing.md`

95. Spelling mistake - Broswer > Browser
96. Spelling mistake - neeeded > needed
97. Spelling mistake - incompatabiliites > incompatibilities

In `src/blog/_posts/2008-09-10-the-opera-9-6-family-nothing-left-behind.md`

98. Remove extra a

In `src/blog/_posts/2008-08-31-open-the-web-update-livejournal.md`

99. Spelling mistake - Califronia > California

In `src/blog/_posts/2008-08-27-two-cheers-for-the-target-nfb-accessility-settlement.md`

100. Spelling mistake - inaccessiiblity > inaccessibility

In `src/blog/_posts/2008-08-18-video-on-the-web.md`

101. Remove extra the
102. Replace a with an ( 2 instances )

In `src/blog/_posts/2008-08-13-css-3-image-replacement.md`

103. Replace an with a

In `src/blog/_posts/2008-08-07-welcome-to-the-opera-developer-network.md`

104. Spelling mistake - wil > will

In `src/blog/_posts/2008-06-05-engineering-seminar.md`

105. Spelling mistake - interal > internal

In `src/blog/_posts/2008-05-26-new-kestrel-snapshot-fixes-opera-dragonfly-issues.md`

106. Spelling mistake - programatically > programmatically

In `src/blog/_posts/2008-05-22-first-weekly-build-now-live.md`

107. Replace a with an

In `src/blog/_posts/2008-04-10-opera-mini-for-android.md`

108. Spelling mistake - resourses > resources
109. Spelling mistake - comparitively > comparatively

In `src/blog/_posts/2007-04-17-a-call-for-video-on-the-web.md`

110. Spelling mistake - tranfer > transfer
111. Remove extra the

In `src/blog/_posts/2006-11-09-introducing-extended-validation-certificates.md`

112. Spelling mistake - assiociated > associated
113. Spelling mistake - guidlines > guidelines
114. Spelling mistake - trusthworty > trustworthy
115. Spelling mistake - critera > criteria

In `src/blog/_posts/2006-09-01-event-streaming-to-web-browsers.md`

116. Spelling mistake - continously > continuously
117. Spelling mistake - anyhing > anything
118. Replace a with an

In `src/blog/_posts/2006-05-10-debugging-svg.md`

119. Spelling mistake - frustrasting > frustrating

In `src/articles/_posts/2007-11-07-a-call-for-video-on-the-web-opera-video-release-on-labs.md`

120. Remove extra should

In `src/articles/_posts/2008-02-29-photoshop-like-effects-in-svg.md`

121. Spelling mistake - explaination > explanation

**Comment by pepelsbey** [comment]
@pra85, thank you for the great fixes, please give us some time to review your PR

**Comment by pra85** [comment]
Sure @pepelsbey 

As the changes introduced are a lot, it would be good to review (as I also wouldn't want this PR to become counterproductive, in the sense that it ends up introducing typos rather than fixing them). Feel free to tag me in inline comments where necessary.

Sorry to overburden you with more typos, but I pushed another batch of changes ( this is the last one, no more typos incoming :) ). Here is the detailed information about the changes in the last commit  -

In `src/articles/_posts/2008-07-08-html-basics.md`

122. Spelling mistake - paragrahs > paragraphs

In `src/articles/_posts/2008-08-28-zebra-striping-tables-with-css3.md`

123. Spelling mistake - sucessfully > successfully
124. Replace an with a
125. Spelling mistake - browers > browsers

In `src/articles/_posts/2008-09-10-opera-binary-markup-language.md`

126. Spelling mistake - cavets > caveats

In `src/articles/_posts/2008-09-26-css-basics.md`

127. Spelling mistake - delimeters > delimiters
128. Spelling mistake - Descendent > Descendant ( 10 instances - Refer https://www.w3.org/TR/CSS21/selector.html#descendant-selectors )
129. Spelling mistake - hexidecimal > hexadecimal

In `src/articles/_posts/2008-10-01-automatic-numbering-with-css-counters.md`

130. Replace a with an ( 2 instances )

In `src/articles/_posts/2008-12-28-3d-games-with-canvas-and-raycasting-part-1.md`

131. Spelling mistake - indentical > identical

In `src/articles/_posts/2009-01-08-html5-canvas-basics.md`

132. Spelling mistake - supportd > supported

In `src/articles/_posts/2009-01-15-raphael-javascript-api-for-svg.md`

133. Spelling mistake - appearence > appearance

In `src/articles/_posts/2009-03-06-javascript-best-practices.md`

134. Spelling mistake - appproach > approach
135. Spelling mistake - degredation > degradation
136. Spelling mistake - amongts > amongst

In `src/articles/_posts/2009-03-13-3d-games-with-canvas-and-raycasting-part-2.md`

137. Spelling mistake - whereever > wherever

In `src/articles/_posts/2009-04-22-javascript-for-hackers.md`

138. Replace a with an ( 3 instances)

In `src/articles/_posts/2009-09-01-hsl-rgb-and-alpha-transparency.md`

139. Spelling mistake - intutive > intuitive

In `src/articles/_posts/2009-09-23-adding-meaning-to-http-error-pages.md`

140. Remove extra the
141. Remove extra and
142. Spelling mistake - addess > address

In `src/articles/_posts/2009-12-22-css3-borders-backgrounds-boxes.md`

141. Remove extra not

In `src/articles/_posts/2010-02-04-svg-or-canvas-choose.md`

142. Spelling mistake - annouced > announced ( 2 instances )

In `src/articles/_posts/2010-02-11-introduction-html5-video.md`

143. Spelling mistake - specifiy > specify
144. Spelling mistake - succesfully > successfully

In `src/articles/_posts/2010-03-10-everything-you-need-to-know-html5-video-audio.md`

145. Spelling mistake - enugh > enough
146. Replace a with an autoplay
147. Spelling mistake - atributes > attributes

In `src/articles/_posts/2010-07-01-offline-applications-html5-appcache.md`

148. Remove extra the ( 2 instances )
149. Spelling mistake - exampple > example
150. Spelling mistake - untill > until

In `src/articles/_posts/2010-07-06-html5-audio-radio-player.md`

151. Remove extra in
152. Spelling mistake - contaning > containing
153. Replace a with an ( 2 instances )

In `src/articles/_posts/2010-07-28-mobile-web-optimization-guide.md`

154. Replace an with a
155. Spelling mistake - ehancement > enhancement
156. Spelling mistake - docmented > documented

In `src/articles/_posts/2010-12-16-new-form-features-in-html5.md`

157. Spelling mistake - brower > browser
158. Spelling mistake - mnagement > management

In `src/articles/_posts/2010-12-21-new-structural-elements-in-html5.md`

159. Remove extra for
160. Spelling mistake - condidates > candidates
161. Remove extra have
162. Remove extra the

In `src/articles/_posts/2011-01-06-css3-object-fit-object-position.md`

163. Spelling mistake - ignorse > ignore
164. Remove extra a

In `src/articles/_posts/2011-02-11-opera-mini-content-authoring-guidelines.md`

165. Spelling mistake - scrools > scrolls

In `src/articles/_posts/2011-02-23-javascript-array-extras-in-detail.md`

166. Spelling mistake - dicussed > discussed

In `src/articles/_posts/2011-03-17-css3-linear-gradients.md`

167. Spelling mistake - multple > multiple

In `src/articles/_posts/2011-03-22-an-introduction-to-meta-viewport-and-viewport.md`

168. Spelling mistake - actived > activated

In `src/articles/_posts/2011-10-19-playing-with-html5-video-and-getusermedia.md`

169. Spelling mistake - targetting > targeting

In `src/articles/_posts/2011-12-14-better-error-handling-with-window-onerror.md`

170. Spelling mistake - paranthesis > parenthesis

In `src/articles/_posts/2012-01-10-getusermedia-access-camera-privacy-ui.md`

171. Remove extra next

In `src/articles/_posts/2012-02-01-window-postmessage-messagechannel.md`

172. Spelling mistake - dicuss > discuss

In `src/articles/_posts/2012-04-25-drag-and-drop.md`

173. Spelling mistake - accesible > accessible

In `src/articles/_posts/2012-04-27-opera-mobile-emulator-webkit-prefix-support.md`

174. Spelling mistake - retreived > retrieved

In `src/articles/_posts/2012-05-23-understanding-the-css-transforms-matrix.md`

175. Remove extra the

In `src/articles/_posts/2012-06-13-responsive-images-problem.md`

176. Spelling mistake - programatically > programmatically

In `src/articles/_posts/2012-10-09-flexbox-basics.md`

177. Replace a with an

In `src/articles/_posts/2012-10-23-network-service-discovery-api.md`

178. Remove extra to
179. Replace a with an

In `src/articles/_posts/2013-04-17-animating-flexboxes-the-lowdown.md`

180. Remove extra can

In `src/articles/_posts/2013-06-12-understanding-3d-transforms.md`

181. Remove extra the

In `src/articles/_posts/2013-07-02-extension-developer-interviews-cottontracks.md`

182. Replace a with an

In `src/articles/_posts/2013-09-06-mutation-observers-tutorial.md`

183. Remove extra of
184. Replace a with an

In `src/articles/_posts/2013-09-26-media-capture-in-mobile-browsers.md`

185. Remove extra specification

In `src/articles/_posts/2014-06-10-css-will-change-property.md`

186. Spelling mistake - bootleneck > bottleneck 
187. Spelling mistake - noticable > noticeable
188. Spelling mistake - mutliple > multiple
189. Spelling mistake - optimzations > optimizations

In `src/articles/_posts/2014-10-10-css-twenty-years-hakon.md`

190. Remove extra want

In `src/articles/_posts/2015-04-22-wifi-ble-javascript.md`

191. Spelling mistake - servor - servo ( Also servo miswritten as server )
192. Remove misplaced the

In `src/articles/_posts/2015-05-11-houdini.md`

193. Spelling mistake - straightjackets > straitjackets

In `src/articles/_posts/2015-06-03-making-sites-work-opera-mini.md`

194. Spelling mistake - backgound > background

In `src/articles/_posts/2015-08-03-on-a-moratorium-on-new-browser-features.md`

195. Spelling mistake - foresaken > forsaken

In `src/articles/_posts/2015-09-04-houdini-f2f-report.md`

196. Spelling mistake - childs > child's
197. Spelling mistake - charaters > characters
198. Spelling mistake - specifiying > specifying

**Comment by pra85** [comment]
@pepelsbey Sorry for bugging you again. Any updates/timelines for when this would be merged. In case, there are any changes that need to be done in this PR anywhere, feel free to mention me.

Also rebased to resolve merge conflicts

**Comment by pepelsbey** [comment]
Briefly went through, that’s a huge job. Thank you!

**Pull request merged**
