### PR TITLE
Andreas' 1 April article

### PR DESCRIPTION
**Pull request by brucelawson**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Let’s put it in the `drafts` folder for now so that we can still deploy safely until then.

**Comment by pepelsbey** [comment]
@mathiasbynens I would rather add `published: false` instead.

**Comment by brucelawson** [comment]
On 27 March 2015 at 15:20, Vadim Makeev <notifications@github.com> wrote:

> @mathiasbynens <https://github.com/mathiasbynens> I would rather add published:
> false instead.
>

in the metadata stuff?

**Comment by mathiasbynens** [comment]
@brucelawson Yep

**Comment by pepelsbey** [comment]
I’ll attach it myself, thanks

**Pull request merged**
