### PR TITLE
Point outdated article to the new update

### PR DESCRIPTION
**Pull request by patrickhlauke**
(Note that the updated article also links back here for reference, so would be good to keep this version around for historical reasons, but add this cross-reference)

### CODE REVIEW

**Comment by fsoder** [comment]
Thanks!

**Comment by patrickhlauke** [comment]
not that i'm in any rush, just wondering: will the live version be updated too? https://dev.opera.com/articles/media-features/

**Comment by fsoder** [comment]
Looks like deployment failed =/. (Setup getting ancient - not sure when I'll be able to look into that.)

**Comment by patrickhlauke** [comment]
no rush, was just checking if it was going to happen at all at some point, or if it was completely abandoned.

**Pull request merged**
