### PR TITLE
CSP-408: Add disclaimer to old tvsdk articles

### PR DESCRIPTION
**Pull request by amustafaopera**

### CODE REVIEW

**Comment by pepelsbey** [comment]
I’ll ask my colleagues from TV department to review this PR, but could you please also change this:
```
<font color="red"><b>Note:</b></font>
```
to this
```
**Note:**
```
It would make it wrapped with `<strong>` tag which is the best possible tag here. We don’t yell at people here. Thank you.

**Comment by amustafaopera** [comment]
hi,

thanks for your feedback. I wasn't aware that writing something in red qualifies as yelling :)

Its to draw attention to importance of text, the reading of which must not be missed.

Given that, is there any other way of adding color to markup without resorting to html?

**Comment by amustafaopera** [comment]
p.s: writing in CAPS usually means shouting/yelling. not sure if the conventions are different in norway?

**Comment by pepelsbey** [comment]
@amustafaopera, sometime people that don’t work for Opera come here and suggest PRs and when it’s our code or articles we decide to merge it or not, when it’s not I look for a person responsible for this. Sometimes people from Opera TV come here and ask to merge some code then I just review it for sanity and merge it. From what I see, you don’t belong to [operasoftware](https://github.com/orgs/operasoftware/people) organization on GitHub and I have no reasons to merge everything you suggest without checking it first. But now my boss got email from your boss, etc. and I see that you’re from Opera TV and I’ll merge it with some fixes. Could you plese join organization mentioned above and ask your colleagues to do the same? It’s better to use your official `@opera.com` emails, but it’s not necessary.

Speaking of fixes: `<font>` element if deprecated a long time ago and we’re trying to stay standard-compliant here. The same for `color=red`: we use existing styles for such things and if there’s nothing suitable we create new ones.

I’ll create a disclamer styles today and merge your PR.

**Comment by amustafaopera** [comment]
hi Vadim,

Thanks for the clarification. It is fine to use any style you wish with the disclaimer, as long as the actual text remains unchanged.

I tried to join that group, but it doesn't look like I can. I think the moderator has to add me. I am using my opera e-mail address: amustafa@opera.com.

Thanks again,
-Mustafa

**Comment by pepelsbey** [comment]
I implemened all changes myself in 9a342828, so I’m closing this PR. That’s how it looks:

localhost-3000-tv-opera-tv-emulator-

**Comment by amustafaopera** [comment]
yes, this looks super. Cheers!

**Pull request closed without merging**
